### ISSUE TITLE
Icon missing for sort tree items

### ISSUE THREAD

**Issue by janniconl** [Nicola1971/MODxFLAT-Theme#2]
https://github.com/modxcms/evolution/issues/532

Deesen has added a new icon above the tree, which gives an error for the Flat theme. it needs to be added to style.php

![naamloos](https://cloud.githubusercontent.com/assets/1488614/14820883/d3c28fd2-0bc8-11e6-9290-2228c03da916.png)

Currently using this one myself: http://fortawesome.github.io/Font-Awesome/icon/sort-numeric-asc/

**Comment by Nicola1971** [comment]
https://github.com/Nicola1971/MODxFLAT-Theme/issues/2

Fixed, Thank you :)
