### ISSUE TITLE
3.0 (Beta 3.5) - New Layout for wide screen on editing documents

### ISSUE THREAD

**Issue by Nicola1971** [Nicola1971/MODxFLAT-Theme#7]
3.0 (Beta 3.5) - A new Layout for wide screen on editing documents with two columns like Revo manager.
Responsive for medium/wide screen

Medium screen layout:
![document-layout-small](https://cloud.githubusercontent.com/assets/7342798/17020573/a7acc936-4f42-11e6-9922-10aa7ae955e8.png)

Wide screen layout:
![document-layout-wide](https://cloud.githubusercontent.com/assets/7342798/17020581/b106a376-4f42-11e6-9feb-afb5666987c3.png)

**Comment by bossloper** [comment]
+1

**Comment by Nicola1971** [comment]
added to public branch 2.5

**Comment by Nicola1971** [comment]
restored original one column layout in 2.5.1: waiting for a way to choose the favourite layout
